#!/bin/bash

#SBATCH -p rome16q # partition (queue)
#SBATCH -N 1 # number of nodes
#SBATCH --ntasks-per-node 1  # number of cores
#SBATCH --cpus-per-task=1
#SBATCH -t 0-00:01 # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --exclusive

export MV2_HOMOGENEOUS_CLUSTER=1
export MV2_ENABLE_AFFINITY=0

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK

ulimit -s 200240

srun ./a.out